# XLC PANDA Versioning & Release Management Mapping
 
options:
  prev_tag: "prev-marker"
 
projects:
  - name: phpipam
    id: 1
    version:
      file: "version.json"
      json: "version"
 
sizes:
  major: [ breaking ]
  minor: [ feat, refactor ]
  patch: [ fix, docs, chore ]
  none: ["*"]
